#!/bin/bash

make &> /dev/null \
    && ./graphProblemSolver -R 1 -F -f -o A_42_9 graphs/difficiles/A_42_9.dot \
    && dot -Tjpg -o sol/A_42_9_Sat.jpg sol/A_42_9_Sat.dot \
    && echo "Resulting graph is sol/A_42_9_Sat.jpg"
